### ISSUE TITLE
Crashes at `0x136460`

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/mcpi-launcher-linux#1]
Right after `SDL_GetWMInfo`, the program crashes when trying to call a non-existent function with non-existent addresses-- right after this call, `XGetWindowAttributes` and `XTranslateCoordinates` are called, followed by `0x136464` with arguments from `XTranslateCoordinates`. 

Patching out this function bypasses this crash, however the program then sees itself in an invalid state and chooses to exit, terminating the EGL instance.

**Comment by JayFoxRox** [comment]
http://sdl.beuc.net/sdl.wiki/SDL_SysWMInfo

Do you fill out the lock/unlock fields? Those could be called.

**Comment by mhsjlw** [comment]
It is extremely likely that those are the functions that are called, as it would make sense that the first call is to lock the context, grab the X11 stuff, call it, then re-lock the context. I will take a look at this right now.

**Comment by mhsjlw** [comment]
Fixed
